FROM ur-alma:latest

#almax
RUN apt install -y ros-melodic-moveit-visual-tools
RUN apt install -y ros-melodic-pcl-conversions
RUN apt install -y ros-melodic-pcl-ros
RUN cd /catkin_ws/src && git clone https://github.com/alma-x/simulation-cv
RUN cd /catkin_ws/src && git clone https://github.com/alma-x/almasim_ur3
RUN cd /catkin_ws/src && git clone https://github.com/alma-x/ur3-control

#RUN /bin/bash -c '. /opt/ros/melodic/setup.bash; cd /catkin_ws;catkin_make'

RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
#RUN echo "source /catkin_ws/devel/setup.bash" >> ~/.bashrc

# Install Freedom scripts
RUN mkdir /freedom
COPY ./freedom_register.py /freedom/
COPY ./freedom_keep_alive.py /freedom/
COPY ./entrypoint.sh /freedom/

ENTRYPOINT service ssh restart && bash
#ENTRYPOINT ["/freedom/entrypoint.sh"]
