FROM ur-alma:latest

#almax
RUN apt install -y ros-melodic-moveit-visual-tools ros-melodic-pcl-conversions ros-melodic-pcl-ros python3-catkin-pkg-modules python3-rospkg-modules
RUN pip3 install --upgrade pip 
RUN pip3 install --user pyqt5  
RUN apt install -y python3-pyqt5 pyqt5-dev-tools qttools5-dev-tools
RUN cd /catkin_ws/src && git clone https://github.com/alma-x/simulation-cv
RUN cd /catkin_ws/src && git clone https://github.com/alma-x/almasim_ur3
RUN cd /catkin_ws/src && git clone https://github.com/alma-x/ur3-control

RUN apt install -y ros-melodic-desktop-full

#RUN /bin/bash -c '. /opt/ros/melodic/setup.bash; cd /catkin_ws;catkin_make'

#RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
#RUN echo "source /catkin_ws/devel/setup.bash" >> ~/.bashrc

# Install Freedom scripts
RUN mkdir /freedom
#COPY ./freedom_register.py /freedom/
#COPY ./freedom_keep_alive.py /freedom/
COPY ./entrypoint/* /freedom/
RUN chmod +x /freedom/START.sh

#ENTRYPOINT service ssh restart && bash
#ENTRYPOINT ["/freedom/entrypoint.sh"]
